export const galleryItems = [
  {
    preview: "./images/portfolio17.webp",
    original: "./images/portfolio17.webp",
    description: "KAWWWA.ONLINE",
    href: "https://kawwwa.online/",
  },
    {
    preview: "./images/portfolio18.webp",
    original: "./images/portfolio18.webp",
    description: "FLY TRANSFERY 24",
    href: "https://flytransfery24.pl/",
  },
  {
    preview: "./images/portfolio15.webp",
    original: "./images/portfolio15.webp",
    description: "FESTIWAL KOBIECOŚCI 108 CUDÓW",
    href: "https://festiwalkobiecosci108cudow.pl/",
  },
  {
    preview: "./images/portfolio14.webp",
    original: "./images/portfolio14.webp",
    description: "MERDAM – salon strzyżenia i pielęgnacji psów",
    href: "https://serwer402735.lh.pl/autoinstalator-home/wordpressplus1/",
  },
  {
    preview: "./images/portfolio16.webp",
    original: "./images/portfolio16.webp",
    description: "Zanzibar Investments Partner",
    href: "https://zip.tz/",
  },
    {
    preview: "./images/portfolio19.webp",
    original: "./images/portfolio19.webp",
    description: "VeltariaGroup Sp. z o.o.",
    href: "https://veltariagroup.com/",
  },
  {
    preview: "./images/portfolio12.webp",
    original: "./images/portfolio12.webp",
    description: "ManiEduTroki Akademia Stylizacji Paznokci - Ewelina Sas",
    href: "https://www.ewelina-sas.pl/",
  },
  // {
  //   preview: "./images/portfolio11.webp",
  //   original: "./images/portfolio11.webp",
  //   description: "Habitare - Sklep online",
  //   href: "http://wordpress2410099.home.pl/autoinstalator/wordpresswoocommerce6/",
  // },
  {
    preview: "./images/portfolio4.webp",
    original: "./images/portfolio4.webp",
    description: "WebStudio - Effective Solutions for Your Business",
    href: "https://achoma.github.io/goit-markup-hw-07/",
  },
  {
    preview: "./images/portfolio9.webp",
    original: "./images/portfolio9.webp",
    description: "Be-Online",
    href: "https://achoma.github.io/be-online/",
  },
  {
    preview: "./images/portfolio6.webp",
    original: "./images/portfolio6.webp",
    description: "SharkBuy - Sklep online",
    href: "https://sharkbuy.pl/",
  },
  {
    preview: "./images/portfolio2.webp",
    original: "./images/portfolio2.webp",
    description: "IceCream",
    href: "https://achoma.github.io/icecream-project/",
  },
  {
    preview: "./images/portfolio3.webp",
    original: "./images/portfolio3.webp",
    description: "Simply Chocolate",
  },
  {
    preview: "./images/portfolio1.webp",
    original: "./images/portfolio1.webp",
    description: "Cats Breeds",
    href: "https://achoma.github.io/the-cats-breeds/",
  },
  {
    preview: "./images/portfolio5.webp",
    original: "./images/portfolio5.webp",
    description: "Photo Search",
    href: "https://achoma.github.io/Photo-Search/",
  },

  {
    preview: "./images/portfolio7.webp",
    original: "./images/portfolio7.webp",
    description: "Filmoteka",
    href: "https://krzysztof-goit.github.io/goit-projekt-filmoteka/",
  },
  {
    preview: "./images/portfolio8.webp",
    original: "./images/portfolio8.webp",
    description: "Cinemania",
    href: "https://magdalenasiniawska.github.io/cinemania_gr2/",
  },
  {
    preview: "./images/portfolio10.webp",
    original: "./images/portfolio10.webp",
    description: "Portfolio",
    href: "https://agnieszkachoma.pl/",
  },
];
